"""first

Revision ID: 6b9badf21062
Revises: 
Create Date: 2022-05-31 20:54:01.089601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b9badf21062'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farm_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region', sa.Integer(), nullable=True),
    sa.Column('are_of_farm', sa.Float(), nullable=True),
    sa.Column('number_of_greenhouse', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Farm info'
    )
    op.create_table('sensor_record',
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('green_house_id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('weather', sa.String(length=500), nullable=True),
    sa.Column('number_of_week', sa.String(length=200), nullable=True),
    sa.Column('sensor_data', sa.String(length=500), nullable=True),
    sa.Column('lint_number', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('farm_id', 'green_house_id', 'sensor_id', 'date'),
    comment='Sensor'
    )
    op.create_table('greenhouse_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('cultivation_area', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farm_information.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='greenhouse_information'
    )
    op.create_table('nutrient_irrigator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('greenhouse_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('position_north', sa.Float(), nullable=True),
    sa.Column('position_west', sa.Float(), nullable=True),
    sa.Column('position_height', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['greenhouse_id'], ['greenhouse_information.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='nutrient_irrigator'
    )
    op.create_table('nutrient_irrigator_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('irrigator_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('weather', sa.String(length=500), nullable=True),
    sa.Column('number_of_week', sa.Integer(), nullable=True),
    sa.Column('single_supply', sa.String(length=100), nullable=True),
    sa.Column('ec', sa.String(length=100), nullable=True),
    sa.Column('line_number', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['irrigator_id'], ['nutrient_irrigator.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='nutrient_irrigator_record'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nutrient_irrigator_record')
    op.drop_table('nutrient_irrigator')
    op.drop_table('greenhouse_information')
    op.drop_table('sensor_record')
    op.drop_table('farm_information')
    # ### end Alembic commands ###
