"""update actuator

Revision ID: e25eea5eb13b
Revises: 471e0c4a7e8f
Create Date: 2022-09-10 12:33:05.687618

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import oracle

# revision identifiers, used by Alembic.
revision = 'e25eea5eb13b'
down_revision = '471e0c4a7e8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actuator', sa.Column('local_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actuator', 'local_id')
    # ### end Alembic commands ###
