"""add label column

Revision ID: f1b1fac19dd4
Revises: e25eea5eb13b
Create Date: 2022-10-15 18:05:54.058159

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import oracle

# revision identifiers, used by Alembic.
revision = 'f1b1fac19dd4'
down_revision = 'e25eea5eb13b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actuator', sa.Column('label', sa.String(length=255), nullable=True))
    op.alter_column('basic_growth_info', 'sow_date_of_seedling',
               existing_type=oracle.DATE(),
               comment='',
               existing_nullable=True)
    op.alter_column('basic_growth_info', 'transplanting_date_of_seedling',
               existing_type=oracle.DATE(),
               comment='',
               existing_nullable=True)
    op.add_column('farm', sa.Column('label', sa.String(length=255), nullable=True))
    op.add_column('greenhouse', sa.Column('label', sa.String(length=255), nullable=True))
    op.add_column('sensor', sa.Column('label', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor', 'label')
    op.drop_column('greenhouse', 'label')
    op.drop_column('farm', 'label')
    op.alter_column('basic_growth_info', 'transplanting_date_of_seedling',
               existing_type=oracle.DATE(),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('basic_growth_info', 'sow_date_of_seedling',
               existing_type=oracle.DATE(),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.drop_column('actuator', 'label')
    # ### end Alembic commands ###
