# Use postgres/example user/password credentials
version: '3.1'

services:

  oracle-db:
    image: tiktzuki/oracle-xe-11g:latest
    restart: always
    ports:
      - 1521:1521
      - 5500:5500
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_PWD=123456