version: '0.0.1'

services:
  oracle-db:
    image: tiktzuki/oracle:21.3.0-ee
    restart: always
    ports:
      - 1521:1521
      - 5500:5500
    environment:
      - ORACLE_PDB=xe
      - ORACLE_PWD=oracle
#      - INIT_SGA_SIZE=3000
#      - INIT_PGA_SIZE=1000
